spring.application.name=grocery-backend
server.port=${PORT:7777}

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.hpbbdqzkxmkjqeczqydb
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.initialization-fail-timeout=5000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# ---- JWT ----
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:8640000000}


app.seed.user1.username=${SEED_USER1_USERNAME}
app.seed.user1.password=${SEED_USER1_PASSWORD}
app.seed.user2.username=${SEED_USER2_USERNAME}
app.seed.user2.password=${SEED_USER2_PASSWORD}


whatsapp.phone-number-id=${WHATSAPP_PHONE_NUMBER_ID}
whatsapp.access-token=${WHATSAPP_ACCESS_TOKEN}


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=2525
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.sendEmail=${SEND_EMAIL_FROM}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:*}

management.endpoints.web.exposure.include=health,metrics